-- begin VALUECHANGEDTESTAPP_ORDER
alter table VALUECHANGEDTESTAPP_ORDER add constraint FK_VALUECHANGEDTESTAPP_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references VALUECHANGEDTESTAPP_CUSTOMER(ID)^
create index IDX_VALUECHANGEDTESTAPP_ORDER_CUSTOMER on VALUECHANGEDTESTAPP_ORDER (CUSTOMER_ID)^
-- end VALUECHANGEDTESTAPP_ORDER
